name: pipelines
on:
  push:
    branches:
      - release
      - development
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: install requirements
      run: ./helper.sh reqs
    - name: check code
      run: ./helper.sh code_check  
    - name: run unit tests
      run: ./helper.sh test
    - name: check coverage
      run: ./helper.sh check_coverage 80
    - name: build
      run: ./helper.sh build
    - name: publish
      if: ${{ github.ref == 'refs/heads/release' }}
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: ./helper.sh publish
